version: "3.7"
services:
  app:
    build:
      args:
        user: paulo
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: homestead
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 33060:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel

  pgsql:
    image: postgres:12.4-alpine
    container_name: laravel-pgsql
    restart: always
    volumes:
      - ./docker-compose/postgres:/var/lib/postgresql/data
    ports:
      - 54320:5432
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "homestead"
      POSTGRES_USER: "homestead"
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel

  pgadmin:
    container_name: laravel-pgadmin
    logging:
      driver: none
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    links:
      - pgsql
    ports:
      - "8086:80"
    depends_on:
      - pgsql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
    links:
      - mysql
    ports:
      - 8085:80
    volumes:
      - /sessions
    networks:
      - laravel

  redis:
    image: "redis:alpine"
    container_name: laravel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  maildev:
    image: djfarrelly/maildev
    container_name: laravel-maildev
    restart: unless-stopped
    expose:
      - 25
    ports:
      - 1080:80
      - 1025:25
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
